#!/usr/bin/env bash

set -e # exit immediately after error

# check if aspell is available for spell checking
aspellInstalled=$([ "$(command -v aspell)" != "" ])

# set this to your active development branch
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# regex to validate branch name
branch_regex='^(fix|feat|chore|ci)\/.*'
error_msg="Aborting commit. Your branch name: '$current_branch' doesn't fit the contributing-guidelines. See: https://gist.github.com/buddiman/628d55d0b08ff0672af5f4c156afeb08"

if $aspellInstalled && [ "$(echo "$current_branch" | aspell list --lang en)" ]; then
  echo "please check spelling for branch: $current_branch" >&2
  exit 1
fi

if ! grep -iqE "$branch_regex" <<< "$current_branch"; then
  echo "$error_msg" >&2
  exit 1
fi

# regex to validate commit msg
commit_regex='^(fix|feat|chore|refactor|ci|docs|test):.*'
commit_message=$(cat "$1")
error_msg="Aborting commit. Your commit message: '$commit_message' doens't fit the contributing-guidelines. See: https://gist.github.com/buddiman/628d55d0b08ff0672af5f4c156afeb08"

if $aspellInstalled && [ "$(echo "$commit_message" | aspell list --lang en)" ]; then
  echo "please check spelling for commit message: $commit_message" >&2
  exit 1
fi

if ! grep -iqE "$commit_regex" "$1"; then
  echo "$error_msg" >&2
  exit 1
fi